export const candidates = [
  "Kadarsuman, SE, MM",
  "Drs. H. Soemarno HS",
  "Ade Bhakti Ariawan, SH",
  "Trivena Veyatin Suhendro, S.kom",
  "Claudyna C. Ningrum",
  "H. Joko Santoso, SE, MM",
  "Swasti Aswagati, S.psi",
  "Hj. Hevearita Gunaryanti Rahayu, M.Sos",
  "Iswar Aminuddin, M.T",
  "H. Arnaz Agung Andrasmarra, SE, MM",
  "Erry Sadewo",
  "A.S. Sukawijaya as Yoyok Sukawi",
  "KH. Anasom",
  "Dr. H. AM Jumai, MM",
];
